### ISSUE TITLE
Server Public ephemeral value is 32 bytes larger than client public ephemeral value.

### ISSUE THREAD

**Issue by dakait** [opencoff/go-srp#5]
According to your documentation:
B = (kv + g^b) % N 
but on 
https://github.com/opencoff/go-srp/blob/c8ec9405e10495ffa1cfe10e81390e2da157a8fb/srp.go#L477 
it seems that you are doing B = kv + (g^b)%N. I think this may be the reason why B is 32 bytes larger in size than A. I think there is problem as it isn't right.
Please help me understand this line of code.

**Comment by opencoff** [comment]
Hello,

You are correct; all arithmetic should've been done mod N. I seem to 
have missed that one.

Thanks for catching it.
--
